C:\Windows\System32\inetsrv\appcmd start apppool / AIGCORP
C:\Windows\System32\inetsrv\appcmd start apppool / Arete
C:\Windows\System32\inetsrv\appcmd start apppool / BSF
C:\Windows\System32\inetsrv\appcmd start apppool / CECEntertainment
C:\Windows\System32\inetsrv\appcmd start apppool / ClientSolutions
C:\Windows\System32\inetsrv\appcmd start apppool / Diebold
C:\Windows\System32\inetsrv\appcmd start apppool / ECOLAB
C:\Windows\System32\inetsrv\appcmd start apppool / FurstStaffing
C:\Windows\System32\inetsrv\appcmd start apppool / GAIC
C:\Windows\System32\inetsrv\appcmd start apppool / IndianaUniversity
C:\Windows\System32\inetsrv\appcmd start apppool / IntegrityInsurance
C:\Windows\System32\inetsrv\appcmd start apppool / KeySolution
C:\Windows\System32\inetsrv\appcmd start apppool / KeySolutionNewCase
C:\Windows\System32\inetsrv\appcmd start apppool / Kroger
C:\Windows\System32\inetsrv\appcmd start apppool / LibertyMutualHomeRepair
C:\Windows\System32\inetsrv\appcmd start apppool / Lumberliquidators
C:\Windows\System32\inetsrv\appcmd start apppool / McDonaldsFieldRecruiting
C:\Windows\System32\inetsrv\appcmd start apppool / McDonaldsStaffRecruiting
C:\Windows\System32\inetsrv\appcmd start apppool / NationalLifeGroup
C:\Windows\System32\inetsrv\appcmd start apppool / Octapharma
C:\Windows\System32\inetsrv\appcmd start apppool / RMHCCF
C:\Windows\System32\inetsrv\appcmd start apppool / SGS
C:\Windows\System32\inetsrv\appcmd start apppool / SpartanOffshore
C:\Windows\System32\inetsrv\appcmd start apppool / Specialty
C:\Windows\System32\inetsrv\appcmd start apppool / spplus
C:\Windows\System32\inetsrv\appcmd start apppool / Tektronix
C:\Windows\System32\inetsrv\appcmd start apppool / TripleplayFM
C:\Windows\System32\inetsrv\appcmd start apppool / USAPARKING
C:\Windows\System32\inetsrv\appcmd start apppool / USPIS
C:\Windows\System32\inetsrv\appcmd start apppool / WALMARTHAEP
C:\Windows\System32\inetsrv\appcmd start apppool / WesternUnionContractors
C:\Windows\System32\inetsrv\appcmd start apppool / WIS
