C:\Windows\System32\inetsrv\appcmd stop apppool / AIGCORP
C:\Windows\System32\inetsrv\appcmd stop apppool / Arete
C:\Windows\System32\inetsrv\appcmd stop apppool / BSF
C:\Windows\System32\inetsrv\appcmd stop apppool / CECEntertainment
C:\Windows\System32\inetsrv\appcmd stop apppool / ClientSolutions
C:\Windows\System32\inetsrv\appcmd stop apppool / Diebold
C:\Windows\System32\inetsrv\appcmd stop apppool / ECOLAB
C:\Windows\System32\inetsrv\appcmd stop apppool / FurstStaffing
C:\Windows\System32\inetsrv\appcmd stop apppool / GAIC
C:\Windows\System32\inetsrv\appcmd stop apppool / IndianaUniversity
C:\Windows\System32\inetsrv\appcmd stop apppool / IntegrityInsurance
C:\Windows\System32\inetsrv\appcmd stop apppool / KeySolution
C:\Windows\System32\inetsrv\appcmd stop apppool / KeySolutionNewCase
C:\Windows\System32\inetsrv\appcmd stop apppool / Kroger
C:\Windows\System32\inetsrv\appcmd stop apppool / LibertyMutualHomeRepair
C:\Windows\System32\inetsrv\appcmd stop apppool / Lumberliquidators
C:\Windows\System32\inetsrv\appcmd stop apppool / McDonaldsFieldRecruiting
C:\Windows\System32\inetsrv\appcmd stop apppool / McDonaldsStaffRecruiting
C:\Windows\System32\inetsrv\appcmd stop apppool / NationalLifeGroup
C:\Windows\System32\inetsrv\appcmd stop apppool / Octapharma
C:\Windows\System32\inetsrv\appcmd stop apppool / RMHCCF
C:\Windows\System32\inetsrv\appcmd stop apppool / SGS
C:\Windows\System32\inetsrv\appcmd stop apppool / SpartanOffshore
C:\Windows\System32\inetsrv\appcmd stop apppool / Specialty
C:\Windows\System32\inetsrv\appcmd stop apppool / spplus
C:\Windows\System32\inetsrv\appcmd stop apppool / Tektronix
C:\Windows\System32\inetsrv\appcmd stop apppool / TripleplayFM
C:\Windows\System32\inetsrv\appcmd stop apppool / USAPARKING
C:\Windows\System32\inetsrv\appcmd stop apppool / USPIS
C:\Windows\System32\inetsrv\appcmd stop apppool / WALMARTHAEP
C:\Windows\System32\inetsrv\appcmd stop apppool / WesternUnionContractors
C:\Windows\System32\inetsrv\appcmd stop apppool / WIS


