C:\Windows\System32\inetsrv\appcmd start apppool / ABCFWS
C:\Windows\System32\inetsrv\appcmd start apppool / AetnaCOV
C:\Windows\System32\inetsrv\appcmd start apppool / ALB
C:\Windows\System32\inetsrv\appcmd start apppool / AMNHealthcare
C:\Windows\System32\inetsrv\appcmd start apppool / ARTVAN
C:\Windows\System32\inetsrv\appcmd start apppool / ASP.NET v4.0
C:\Windows\System32\inetsrv\appcmd start apppool / BodyCentral
C:\Windows\System32\inetsrv\appcmd start apppool / CenteneAmbetter
C:\Windows\System32\inetsrv\appcmd start apppool / EQUITYLIFESTYLE
C:\Windows\System32\inetsrv\appcmd start apppool / Experis
C:\Windows\System32\inetsrv\appcmd start apppool / ExpressScripts
C:\Windows\System32\inetsrv\appcmd start apppool / GMP
C:\Windows\System32\inetsrv\appcmd start apppool / GoDaddy
C:\Windows\System32\inetsrv\appcmd start apppool / GPMLife
C:\Windows\System32\inetsrv\appcmd start apppool / GrangeInsurance
C:\Windows\System32\inetsrv\appcmd start apppool / JAlexanders
C:\Windows\System32\inetsrv\appcmd start apppool / KEMPERBENEFITS
C:\Windows\System32\inetsrv\appcmd start apppool / LIFEMgmt
C:\Windows\System32\inetsrv\appcmd start apppool / PangeaOnlineHelp
C:\Windows\System32\inetsrv\appcmd start apppool / ProtectionOne
C:\Windows\System32\inetsrv\appcmd start apppool / RGARE
C:\Windows\System32\inetsrv\appcmd start apppool / RHI3
C:\Windows\System32\inetsrv\appcmd start apppool / RWOC
C:\Windows\System32\inetsrv\appcmd start apppool / SakConstruction
C:\Windows\System32\inetsrv\appcmd start apppool / STANDARDPARKING
C:\Windows\System32\inetsrv\appcmd start apppool / TETRAPAK
C:\Windows\System32\inetsrv\appcmd start apppool / UNITEDHERITAGE
C:\Windows\System32\inetsrv\appcmd start apppool / USPS
C:\Windows\System32\inetsrv\appcmd start apppool / VCCT
C:\Windows\System32\inetsrv\appcmd start apppool / Walmart