C:\Windows\System32\inetsrv\appcmd stop apppool / ABCFWS
C:\Windows\System32\inetsrv\appcmd stop apppool / AetnaCOV
C:\Windows\System32\inetsrv\appcmd stop apppool / ALB
C:\Windows\System32\inetsrv\appcmd stop apppool / AMNHealthcare
C:\Windows\System32\inetsrv\appcmd stop apppool / ARTVAN
C:\Windows\System32\inetsrv\appcmd stop apppool / ASP.NET v4.0
C:\Windows\System32\inetsrv\appcmd stop apppool / BodyCentral
C:\Windows\System32\inetsrv\appcmd stop apppool / CenteneAmbetter
C:\Windows\System32\inetsrv\appcmd stop apppool / EQUITYLIFESTYLE
C:\Windows\System32\inetsrv\appcmd stop apppool / Experis
C:\Windows\System32\inetsrv\appcmd stop apppool / ExpressScripts
C:\Windows\System32\inetsrv\appcmd stop apppool / GMP
C:\Windows\System32\inetsrv\appcmd stop apppool / GoDaddy
C:\Windows\System32\inetsrv\appcmd stop apppool / GPMLife
C:\Windows\System32\inetsrv\appcmd stop apppool / GrangeInsurance
C:\Windows\System32\inetsrv\appcmd stop apppool / JAlexanders
C:\Windows\System32\inetsrv\appcmd stop apppool / KEMPERBENEFITS
C:\Windows\System32\inetsrv\appcmd stop apppool / LIFEMgmt
C:\Windows\System32\inetsrv\appcmd stop apppool / PangeaOnlineHelp
C:\Windows\System32\inetsrv\appcmd stop apppool / ProtectionOne
C:\Windows\System32\inetsrv\appcmd stop apppool / RGARE
C:\Windows\System32\inetsrv\appcmd stop apppool / RHI3
C:\Windows\System32\inetsrv\appcmd stop apppool / RWOC
C:\Windows\System32\inetsrv\appcmd stop apppool / SakConstruction
C:\Windows\System32\inetsrv\appcmd stop apppool / STANDARDPARKING
C:\Windows\System32\inetsrv\appcmd stop apppool / TETRAPAK
C:\Windows\System32\inetsrv\appcmd stop apppool / UNITEDHERITAGE
C:\Windows\System32\inetsrv\appcmd stop apppool / USPS
C:\Windows\System32\inetsrv\appcmd stop apppool / VCCT
C:\Windows\System32\inetsrv\appcmd stop apppool / Walmart