C:\Windows\System32\inetsrv\appcmd stop apppool / Aetna
C:\Windows\System32\inetsrv\appcmd stop apppool / AetnaACQ
C:\Windows\System32\inetsrv\appcmd stop apppool / AetnaHR
C:\Windows\System32\inetsrv\appcmd stop apppool / AG
C:\Windows\System32\inetsrv\appcmd stop apppool / AmericanEagle
C:\Windows\System32\inetsrv\appcmd stop apppool / CapellaHealthcare
C:\Windows\System32\inetsrv\appcmd stop apppool / Celtic
C:\Windows\System32\inetsrv\appcmd stop apppool / CentralParking
C:\Windows\System32\inetsrv\appcmd stop apppool / Colonial
C:\Windows\System32\inetsrv\appcmd stop apppool / Conns
C:\Windows\System32\inetsrv\appcmd stop apppool / CumminsRockyMountain
C:\Windows\System32\inetsrv\appcmd stop apppool / Daybreak
C:\Windows\System32\inetsrv\appcmd stop apppool / DearbornNational
C:\Windows\System32\inetsrv\appcmd stop apppool / DHP
C:\Windows\System32\inetsrv\appcmd stop apppool / DLAPiper
C:\Windows\System32\inetsrv\appcmd stop apppool / DukeEnergy
C:\Windows\System32\inetsrv\appcmd stop apppool / EastKYPower
C:\Windows\System32\inetsrv\appcmd stop apppool / EMC
C:\Windows\System32\inetsrv\appcmd stop apppool / ForestLabs
C:\Windows\System32\inetsrv\appcmd stop apppool / Genesis
C:\Windows\System32\inetsrv\appcmd stop apppool / GIS
C:\Windows\System32\inetsrv\appcmd stop apppool / GISIntAuth
C:\Windows\System32\inetsrv\appcmd stop apppool / HR1
C:\Windows\System32\inetsrv\appcmd stop apppool / Insurance2
C:\Windows\System32\inetsrv\appcmd stop apppool / Inventiv
C:\Windows\System32\inetsrv\appcmd stop apppool / Jostens
C:\Windows\System32\inetsrv\appcmd stop apppool / LifePoint
C:\Windows\System32\inetsrv\appcmd stop apppool / Manpower
C:\Windows\System32\inetsrv\appcmd stop apppool / McDonalds
C:\Windows\System32\inetsrv\appcmd stop apppool / NewBalanceAthleticShoe
C:\Windows\System32\inetsrv\appcmd stop apppool / OhioNational
C:\Windows\System32\inetsrv\appcmd stop apppool / Owens-Minor
C:\Windows\System32\inetsrv\appcmd stop apppool / ProtectiveLife
C:\Windows\System32\inetsrv\appcmd stop apppool / QBEAmericasInc
C:\Windows\System32\inetsrv\appcmd stop apppool / RHITraining
C:\Windows\System32\inetsrv\appcmd stop apppool / Securus
C:\Windows\System32\inetsrv\appcmd stop apppool / SEFL
C:\Windows\System32\inetsrv\appcmd stop apppool / SharpElectronics
C:\Windows\System32\inetsrv\appcmd stop apppool / ShoeCarnival
C:\Windows\System32\inetsrv\appcmd stop apppool / Sitel
C:\Windows\System32\inetsrv\appcmd stop apppool / StanleySteemer
C:\Windows\System32\inetsrv\appcmd stop apppool / StarTek
C:\Windows\System32\inetsrv\appcmd stop apppool / StateAuto
C:\Windows\System32\inetsrv\appcmd stop apppool / TalismanEnergy
C:\Windows\System32\inetsrv\appcmd stop apppool / Timberland
C:\Windows\System32\inetsrv\appcmd stop apppool / Unum
C:\Windows\System32\inetsrv\appcmd stop apppool / WesternUnion